<a href="https://colab.research.google.com/github/rbespin/FoodWaterLoss/blob/master/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#HW1 Robert Espinoza

In [ ]:
#Problem 1
import tensorflow as tf
print(tf.__version__)

import keras as ks
print(ks.__version__)

2.3.0
2.4.3


In [ ]:
#Problem 2
# Create a constant tensor ‘x’ with values from 100 to 109.
# Create a constant tensor ‘y’ with values 34, 28, 45, 67, 89, 93, 24, 49, 11, 7
# Add tensor ‘x’ and ‘y’
x = tf.constant([100,101,102,103,104,105,106,107,108,109])
y = tf.constant([34,28,45,67,89,93,24,49,11,7])
sum = tf.add(x,y)
print(sum)

tf.Tensor([134 129 147 170 193 198 130 156 119 116], shape=(10,), dtype=int32)


In [ ]:
#Problem 3
# Suppose ‘x1’ a tensor of shape (2,4).
#   x1 = tf.constant([[1,2,3,4],[5,6,7,8]])
# Create a new tensor with shape of (4,2,4) using ‘tf.stack’ function.
x1 = tf.constant([[1,2,3,4],[5,6,7,8]])
x1 = tf.stack([x1,x1,x1,x1])
print(x1)

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]], shape=(4, 2, 4), dtype=int32)


In [ ]:
# Problem 4
# Suppose ‘x1’ a tensor of shape (2,4).
#   x1 = tf.constant([[1,2,3,4],[5,6,7,8]])
# Create a new tensor with shape of (1,2,4).
x1 = tf.constant([[1,2,3,4],[5,6,7,8]])
x1 = tf.stack([x1])
print(x1)

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]], shape=(1, 2, 4), dtype=int32)


In [ ]:
# Problem 5
# Suppose ‘x1’ a tensor of shape (3,4).
#   x1 = tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# Re-shape this tensor into a new tensor of shape (6,2). Print the values of the
#  new tensor.
x1 = tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x1 = tf.reshape(x1,[6,2])
print(x1)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]], shape=(6, 2), dtype=int32)


In [ ]:
# Problem 6
# If variables a, b, c, d, and f are scalars, write TensorFlow programs to 
# compute and display the following expressions. Test your statements for 
# the following values.
# a = 1.12, b = 2.34, c = 0.72, d = 0.81, f = 19.83

In [ ]:
# This function assumes shape (:,1,5) with [a,b,c,d,f]
def compute_x(tensor):
  a = tensor[:,0]
  b = tensor[:,1]
  c = tensor[:,2]
  f = tensor[:,4]
  return(tf.add(tf.add(1,tf.divide(a,b)),tf.divide(c,tf.square(f))))


In [173]:
# This function assumes shape (:,1,5) with [a,b,c,d,f]
def compute_s(tensor):
  a = tensor[:,0]
  b = tensor[:,1]
  c = tensor[:,2]
  d = tensor[:,3]
  return(tf.divide(tf.subtract(b,a),tf.subtract(d,c)))

In [ ]:
# This function assumes shape (:,1,5) with [a,b,c,d,f]
def compute_r(tensor):
  a = tensor[:,0]
  b = tensor[:,1]

  c = tensor[:,2]
  d = tensor[:,3]
  element_one = tf.divide(1,a)
  element_two = tf.divide(1,b)
  element_three = tf.divide(1,c)
  element_four = tf.divide(1,d)
  sum_one_two = tf.add(element_one,element_two)
  sum_three_four = tf.add(element_three,element_four)
  divisor = tf.add(sum_one_two,sum_three_four)
  return(tf.divide(1,divisor))

In [ ]:
# This function assumes shape (:,1,5) with [a,b,c,d,f]
def compute_y(tensor):
  a = tensor[:,0]
  b = tensor[:,1]
  c = tensor[:,2]
  f = tensor[:,4]
  element_one = tf.multiply(a,b)
  element_two = tf.divide(1,c)
  element_three = tf.divide(tf.square(f),2)
  divisor = tf.multiply(tf.multiply(element_one,element_two),element_three)
  return( divisor )

In [ ]:
a = 1.12
b = 2.34
c = 0.72
d = 0.81
f = 19.83
tensor = tf.constant([a,b,c,d,f])

In [ ]:
print(compute_x(tf.stack([tensor])))
print(compute_s(tf.stack([tensor])))
print(compute_r(tf.stack([tensor])))
print(compute_y(tf.stack([tensor])))

tf.Tensor([1.4804634], shape=(1,), dtype=float32)
tf.Tensor([13.555558], shape=(1,), dtype=float32)
tf.Tensor([0.25357127], shape=(1,), dtype=float32)
tf.Tensor([715.6765], shape=(1,), dtype=float32)


In [ ]:
# Peforming same operations with higher dimensional tensors
a = 1.12
b = 2.34
c = 0.72
d = 0.81
f = 19.83
tensor = tf.constant([a,b,c,d,f])
tensor2 = tf.constant([1.0,1.0,1.0,1.0,1.0])
tensor_combination = tf.stack([tensor,tensor2])
print(compute_x(tensor_combination))
print(compute_s(tensor_combination))
print(compute_r(tensor_combination))
print(compute_y(tensor_combination))

tf.Tensor([1.4804634 3.       ], shape=(2,), dtype=float32)
tf.Tensor([13.555558       nan], shape=(2,), dtype=float32)
tf.Tensor([0.25357127 0.25      ], shape=(2,), dtype=float32)
tf.Tensor([7.156765e+02 5.000000e-01], shape=(2,), dtype=float32)


In [ ]:
# Problem 7a
A = tf.constant([[4,-2,1],[6,8,-5],[7,9,10]])
B = tf.constant([[6,9,-4],[7,5,3],[-8,2,1]])
C = tf.constant([[-4,-5,2],[10,6,1],[3,-9,8]])
print(tf.matmul(A,tf.add(B,C)))
print(tf.add(tf.matmul(A,B),tf.matmul(A,C)))
print((tf.matmul(A,tf.add(B,C)))==(tf.add(tf.matmul(A,B),tf.matmul(A,C))))

tf.Tensor(
[[-31 -13  -7]
 [173 147 -25]
 [117  57 112]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[-31 -13  -7]
 [173 147 -25]
 [117  57 112]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]], shape=(3, 3), dtype=bool)


In [175]:
# Problem 7b
A = tf.constant([[4,-2,1],[6,8,-5],[7,9,10]])
B = tf.constant([[6,9,-4],[7,5,3],[-8,2,1]])
C = tf.constant([[-4,-5,2],[10,6,1],[3,-9,8]])

In [177]:
print(tf.matmul(tf.matmul(A,B),C))
print(tf.matmul(A,tf.matmul(B,C)))
print(tf.matmul(tf.matmul(A,B),C) == tf.matmul(A,tf.matmul(B,C)))

tf.Tensor(
[[ 209  347 -136]
 [ 297 -111  308]
 [1207  562  250]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 209  347 -136]
 [ 297 -111  308]
 [1207  562  250]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]], shape=(3, 3), dtype=bool)
